// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"log"
)

// Injectors from wire.go:

func initializeFooBar() *FooBar {
	foo := ProvideFoo()
	bar := ProvideBar()
	fooBar := &FooBar{
		MyFoo: foo,
		MyBar: bar,
	}
	return fooBar
}

// wire.go:

type Foo int

type Bar int

func ProvideFoo() Foo {
	return Foo(1)
}

func ProvideBar() Bar {
	return Bar(2)
}

type FooBar struct {
	MyFoo Foo
	MyBar Bar
}

var Set = wire.NewSet(
	ProvideFoo,
	ProvideBar, wire.Struct(new(FooBar), "MyFoo", "MyBar"))

func main() {
	fooBar := initializeFooBar()
	log.Printf("%#v", fooBar)
}
